services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres_container
    volumes:
      - db:/data/postgres_container
    ports:
      - 5332:5432
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: